### ISSUE TITLE
Problems getting started

### ISSUE THREAD

**Issue by buchgeher** [atlanmod/NeoEMF#2] opened 2015-09-14 09:06 UTC
Hi, 

I have installed NeoEMF using the provided update site (http://atlanmod.github.io/NeoEMF/) in Eclipse 4.4.2. 

I have created a sample plug-in consisting of a simple EMF model as well as some sample code for creating and storing an EMF model. However, when I run my plug-in I get an NoClassDefFoundError (see stack trace below).

Am I missing some additional configuration code, or some additionally required plug-ins? 

Best Regards,
Georg

Sample Code:

PersistenceBackendFactoryRegistry.getFactories().put(NeoBlueprintsURI.NEO_GRAPH_SCHEME, 
			    new BlueprintsPersistenceBackendFactory());
		ResourceSet resSet = new ResourceSetImpl();
		resSet.getResourceFactoryRegistry().getProtocolToFactoryMap().
		    put(NeoBlueprintsURI.NEO_GRAPH_SCHEME, new PersistentResourceFactoryImpl());
		Resource resource = resSet.createResource(
		    NeoBlueprintsURI.createNeoGraphURI(new File("d:\\neodbtest")));
		SampleModel sampleModel = SampleFactory.eINSTANCE.createSampleModel();
		resource.getContents().add(sampleModel);
		try {
		    resource.save(Collections.EMPTY_MAP);
		} catch(IOException e) {
		    e.printStackTrace();
		}

Stack Trace:
org.osgi.framework.BundleException: Exception in neoemfsample.Activator.start() of bundle neoemfsample.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/Type
	at net.sf.cglib.core.TypeUtils.parseType(TypeUtils.java:184)
	at net.sf.cglib.core.KeyFactory.<clinit>(KeyFactory.java:66)
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
	at fr.inria.atlanmod.neoemf.core.impl.NeoEObjectAdapterFactoryImpl.getAdapter(NeoEObjectAdapterFactoryImpl.java:58)
	at fr.inria.atlanmod.neoemf.resources.impl.PersistentResourceImpl$ResourceContentsEStoreEList.delegateAdd(PersistentResourceImpl.java:310)
	at org.eclipse.emf.ecore.impl.EStoreEObjectImpl$BasicEStoreEList.delegateAdd(EStoreEObjectImpl.java:194)
	at org.eclipse.emf.common.util.DelegatingEList.addUnique(DelegatingEList.java:308)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.doAddUnique(DelegatingNotifyingListImpl.java:317)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.addUnique(DelegatingNotifyingListImpl.java:301)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:303)
	at neoemfsample.Activator.test(Activator.java:77)
	at neoemfsample.Activator.start(Activator.java:44)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.Type cannot be found by fr.inria.atlanmod.neoemf.core_0.0.1.SNAPSHOT
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 28 more
Root exception:
java.lang.NoClassDefFoundError: org/objectweb/asm/Type
	at net.sf.cglib.core.TypeUtils.parseType(TypeUtils.java:184)
	at net.sf.cglib.core.KeyFactory.<clinit>(KeyFactory.java:66)
	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
	at fr.inria.atlanmod.neoemf.core.impl.NeoEObjectAdapterFactoryImpl.getAdapter(NeoEObjectAdapterFactoryImpl.java:58)
	at fr.inria.atlanmod.neoemf.resources.impl.PersistentResourceImpl$ResourceContentsEStoreEList.delegateAdd(PersistentResourceImpl.java:310)
	at org.eclipse.emf.ecore.impl.EStoreEObjectImpl$BasicEStoreEList.delegateAdd(EStoreEObjectImpl.java:194)
	at org.eclipse.emf.common.util.DelegatingEList.addUnique(DelegatingEList.java:308)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.doAddUnique(DelegatingNotifyingListImpl.java:317)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.addUnique(DelegatingNotifyingListImpl.java:301)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:303)
	at neoemfsample.Activator.test(Activator.java:77)
	at neoemfsample.Activator.start(Activator.java:44)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.Type cannot be found by fr.inria.atlanmod.neoemf.core_0.0.1.SNAPSHOT
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 28 more

**Comment by gdaniel** [comment] 2015-09-14 10:06
Hi,

It seems to be an update site error, this issue was resolved previously but it hasn't been propagated.
I'll fix it in the afternoon.

Gwendal

**Comment by gdaniel** [comment] 2015-09-14 16:35
Hi again,

Are you using Luna (Eclipse Modeling Tool) or another version?

**Comment by buchgeher** [comment] 2015-09-14 16:39
Hi,

I have tried NeoEMF with the "Eclipse IDE for Eclipse Committers 4.4.2“ version. 

Georg

**Comment by gdaniel** [comment] 2015-09-14 17:10
I am not able to reproduce it.
I tried your sample code in a fresh eclipse installation, after installing NeoEMF plugins from the update site and everything went fine.

Are you able to reproduce it in a new Eclipse installation?

**Comment by buchgeher** [comment] 2015-09-15 07:58
Unfortunately I can reproduce my problem with a new Eclipse installation. 
I have tried a fresh installation of the Luna SR2 Modelling version under Windows 7 as well as a a Mars Modelling version under OSX. 

When I try to start my sample plug-in manually via the OSGi console I get the following bundle exception: java.lang.NoClassDefFoundError: Could not initialize class net.sf.cglib.proxy.Enhancer

In both cases I have installed the following features from the update site:
-NeoEMF Persistence framework
-NeoEMF Blueprints Adapters
-NeoEMF Blueprints Implementations

My sample plug-in can be found under https://dl.dropboxusercontent.com/u/366920/neoemf.zip 

Could you provide a small working example as part of the github project?

**Comment by gdaniel** [comment] 2015-09-17 11:58
Hi again, sorry for the delay.

I fixed the error, you can update your NeoEMF installation from the update site (http://atlanmod.github.io/NeoEMF/). 
Even if the error you pointed out is solved, there is still some problem with your code: your generator model uses the standard importer "Ecore model" instead of the NeoEMF importer "Ecore model (NeoEMF native)".
This force NeoEMF to adapt standard EMF objects to NeoEMF ones, and this feature is not implemented yet. So your code should throw and UnsupportedOperationException.

For the moment, the only solution for this problem is to use the NeoEMF importer to create the generator model. The generated Java code will then be usable directly by NeoEMF.

We also plan to provide working example and backend options in the wiki.

Thanks for the feedback, I close the issue, feel free to reopen it if you still have problems.

**Comment by buchgeher** [comment] 2015-09-21 10:43
Hi,

I have updated my NeoEMF installation from the provided update site. Further, I have migrated my generator model. Unfortunately, now I get an exception that the Graphfactory could not be instantiated (see stack trace 1 below). 

Is there a (rough) timeframe when you will implement the support for native EMF objects without a dedidcated generator model? 


I have also tried to use MapDB as backend. In this case I am getting anther class not found exception, see stack trace 2 below).

Does MapDB also require the dedicated generator model?

Best regards and thanks for your help
Georg

Stack Trace 1:
fr.inria.atlanmod.neoemf.datastore.InvalidDataStoreException: java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [com.tinkerpop.blueprints.impls.tg.TinkerGraph].
	at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackendFactory.createPersistentBackend(BlueprintsPersistenceBackendFactory.java:159)
	at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackendFactory.createPersistentBackend(BlueprintsPersistenceBackendFactory.java:46)
	at fr.inria.atlanmod.neoemf.resources.impl.PersistentResourceImpl.save(PersistentResourceImpl.java:163)
	at neoemfsample.Activator.test(Activator.java:103)
	at neoemfsample.Activator.access$0(Activator.java:79)
	at neoemfsample.Activator$1.run(Activator.java:53)
	at neoemfsample.Activator.start(Activator.java:56)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [com.tinkerpop.blueprints.impls.tg.TinkerGraph].
	at com.tinkerpop.blueprints.GraphFactory.open(GraphFactory.java:48)
	at fr.inria.atlanmod.neoemf.graph.blueprints.datastore.BlueprintsPersistenceBackendFactory.createPersistentBackend(BlueprintsPersistenceBackendFactory.java:157)
	... 22 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.tinkerpop.blueprints.GraphFactory.open(GraphFactory.java:41)
	... 23 more
Caused by: java.lang.RuntimeException: d:\neodbtest\tinkergraph.dat (The system cannot find the file specified)
	at com.tinkerpop.blueprints.impls.tg.TinkerGraph.init(TinkerGraph.java:144)
	at com.tinkerpop.blueprints.impls.tg.TinkerGraph.<init>(TinkerGraph.java:106)
	... 28 more
Caused by: java.io.FileNotFoundException: d:\neodbtest\tinkergraph.dat (The system cannot find the file specified)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:131)
	at java.io.FileInputStream.<init>(FileInputStream.java:87)
	at com.tinkerpop.blueprints.impls.tg.TinkerStorageFactory$JavaTinkerStorage.load(TinkerStorageFactory.java:180)
	at com.tinkerpop.blueprints.impls.tg.TinkerGraph.init(TinkerGraph.java:134)
	... 29 more






Stack Trace 2:
org.osgi.framework.BundleException: Exception in neoemfsample.Activator.start() of bundle neoemfsample.
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:792)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang/ArrayUtils
	at fr.inria.atlanmod.neoemf.map.datastore.estores.impl.DirectWriteMapResourceEStoreImpl.add(DirectWriteMapResourceEStoreImpl.java:185)
	at fr.inria.atlanmod.neoemf.map.datastore.estores.impl.DirectWriteMapResourceEStoreImpl.add(DirectWriteMapResourceEStoreImpl.java:163)
	at org.eclipse.emf.ecore.impl.EStoreEObjectImpl$BasicEStoreEList.delegateAdd(EStoreEObjectImpl.java:188)
	at fr.inria.atlanmod.neoemf.resources.impl.PersistentResourceImpl$ResourceContentsEStoreEList.delegateAdd(PersistentResourceImpl.java:321)
	at org.eclipse.emf.ecore.impl.EStoreEObjectImpl$BasicEStoreEList.delegateAdd(EStoreEObjectImpl.java:194)
	at org.eclipse.emf.common.util.DelegatingEList.addUnique(DelegatingEList.java:308)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.doAddUnique(DelegatingNotifyingListImpl.java:317)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.addUnique(DelegatingNotifyingListImpl.java:301)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:303)
	at neoemfsample.Activator.test(Activator.java:95)
	at neoemfsample.Activator.access$0(Activator.java:75)
	at neoemfsample.Activator$1.run(Activator.java:49)
	at neoemfsample.Activator.start(Activator.java:52)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.ArrayUtils cannot be found by fr.inria.atlanmod.neoemf.map_0.0.1.201509171044
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
Root exception:
java.lang.NoClassDefFoundError: org/apache/commons/lang/ArrayUtils
	at fr.inria.atlanmod.neoemf.map.datastore.estores.impl.DirectWriteMapResourceEStoreImpl.add(DirectWriteMapResourceEStoreImpl.java:185)
	at fr.inria.atlanmod.neoemf.map.datastore.estores.impl.DirectWriteMapResourceEStoreImpl.add(DirectWriteMapResourceEStoreImpl.java:163)
	at org.eclipse.emf.ecore.impl.EStoreEObjectImpl$BasicEStoreEList.delegateAdd(EStoreEObjectImpl.java:188)
	at fr.inria.atlanmod.neoemf.resources.impl.PersistentResourceImpl$ResourceContentsEStoreEList.delegateAdd(PersistentResourceImpl.java:321)
	at org.eclipse.emf.ecore.impl.EStoreEObjectImpl$BasicEStoreEList.delegateAdd(EStoreEObjectImpl.java:194)
	at org.eclipse.emf.common.util.DelegatingEList.addUnique(DelegatingEList.java:308)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.doAddUnique(DelegatingNotifyingListImpl.java:317)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.addUnique(DelegatingNotifyingListImpl.java:301)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:303)
	at neoemfsample.Activator.test(Activator.java:95)
	at neoemfsample.Activator.access$0(Activator.java:75)
	at neoemfsample.Activator$1.run(Activator.java:49)
	at neoemfsample.Activator.start(Activator.java:52)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:771)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:764)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:721)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:936)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:319)
	at org.eclipse.osgi.container.Module.doStart(Module.java:571)
	at org.eclipse.osgi.container.Module.start(Module.java:439)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.ArrayUtils cannot be found by fr.inria.atlanmod.neoemf.map_0.0.1.201509171044
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more

**Comment by abelgomez** [comment] 2015-09-21 10:56
Hi @buchgeher ,

for the first stack trace, I have experienced that problem when a first attempt to create a graph failed (e.g. the problem you had on the first time) and an unusable graph file has been left in the file system.

Does the folder d:\neodbtest\ (with its contained files) exist before running your test code? Does your code run correctly if you delete them before running your test code?

For the second stack trace, seems to be a packaging issue (we changed the build system recently and that's why some problems still arise). I suppose that @gdaniel can assist you on this issue.

Abel

**Comment by gdaniel** [comment] 2015-09-21 11:33
I am on it.
Can you confirm the graph problem is related to an existing directory?

As @abelgomez said, we rencently changed the build system, and there are some bugs related to OSGI. I will do some tests on that.

All the NeoEMF implementations need the NeoEMF genmodel. This is not related to the backend. So MapDB implementation should throw an UnsupportedOperationException like the graph implementation.
Unfortunately I cannot give you a time frame for the standard EMF adapter.

Gwendal

**Comment by buchgeher** [comment] 2015-09-21 11:43
Hi,
deleting the directory solves my issue. I had to delete the entire directory, not only its contents.

Georg

**Comment by gdaniel** [comment] 2015-09-22 11:41
Hi again,

I published a new version of the update site with a quick fix for the NoClassDefFoundError using MapDB. Please update your installation to correct the issue.
Once again, thank you for the feedback.

@abelgomez The solution is not optimal for the moment, I'll rethink the packaging of shared libraries when I'll have more time to do this.

Gwendal

**Closed** 2015-09-22 11:42 UTC
Labels: bug, Packaging
