### ISSUE TITLE
References across models cannot be stored

### ISSUE THREAD

**Issue by rju** [atlanmod/NeoEMF#106] opened 2018-12-03 16:14 UTC
Hi folks,

I have a strange issue when working with two models and references between both models. I prepared an minimal example Eclipse-project to illustrate the issue. This might be related to ticket #97, but I have the impression this is a different issue.

Derived from the NeoEMF tutorial (1.0.2) example, I have two metamodels
- graph
- reference

The illustrative example can be found here:
https://github.com/rju/neoemf-example

**graph** contains three classes _Graph_, _Edge_ and _Vertice_, while **reference** contains only one class called _Reference_.

Initially, I create a graph model with two _Vertices_ and one _Edge_. Then I create a reference model with one instance of _Reference_. _Reference_ has one EReference pointing to the Edge object of the graph. Subsequently, I add first the **graph** and then the **reference** model to their respective resources.

While adding to the graph resource works, adding the reference model to its resource fails with an IllegalArgumentException
`xception in thread "main" java.lang.IllegalArgumentException: given element was not created in this graph
	at com.tinkerpop.blueprints.util.wrappers.id.IdGraph.verifyNativeElement(IdGraph.java:432)
	at com.tinkerpop.blueprints.util.wrappers.id.IdGraph.addEdge(IdGraph.java:199)
	at fr.inria.atlanmod.neoemf.data.blueprints.BlueprintsPersistenceBackend$AutoCleanerIdGraph.addEdge(BlueprintsPersistenceBackend.java:499)
	at com.tinkerpop.blueprints.util.wrappers.id.IdVertex.addEdge(IdVertex.java:51)
	at fr.inria.atlanmod.neoemf.data.blueprints.store.DirectWriteBlueprintsStore.setReference(DirectWriteBlueprintsStore.java:189)
	at fr.inria.atlanmod.neoemf.data.store.AbstractDirectWriteStore.set(AbstractDirectWriteStore.java:106)
	at fr.inria.atlanmod.neoemf.core.DefaultPersistentEObject.resource(DefaultPersistentEObject.java:159)
	at fr.inria.atlanmod.neoemf.resource.DefaultPersistentResource$ResourceContentsEStoreEList.delegateAdd(DefaultPersistentResource.java:454)
	at org.eclipse.emf.ecore.impl.EStoreEObjectImpl$BasicEStoreEList.delegateAdd(EStoreEObjectImpl.java:194)
	at org.eclipse.emf.common.util.DelegatingEList.addUnique(DelegatingEList.java:308)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.doAddUnique(DelegatingNotifyingListImpl.java:317)
	at org.eclipse.emf.common.notify.impl.DelegatingNotifyingListImpl.addUnique(DelegatingNotifyingListImpl.java:301)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:304)
	at example.ExampleTutorial.main(ExampleTutorial.java:56)`

When the _Reference_ object's EReference property is not set, the whole thing works. However, with a proper set reference it fails.

Is this a limitation of NeoEMF, is this a bug or am I missing something?

Kind regards
Reiner

**Comment by gdaniel** [comment] 2018-12-06 11:49
Hi Reiner,

This is a limitation of NeoEMF, we didn't implement the EMF proxy mechanism because it was not on top of our priorities (our use cases usually involve a single, very large model). However, I recently discussed with several people who need to have this feature implemented in the framework to combine and query multiple large models.

This requires to update the implementation of all the backends to support this new feature (especially if we want to resolve proxies efficently). I cannot give you an expected date for this feature, but I'll post in this issue any update regarding proxy resolution in NeoEMF.

Regards,

Gwendal

**Comment by yvernageau** [comment] 2019-03-22 18:20
Duplicate of #97

**Closed by yvernageau** 2019-03-22 18:20 UTC
Labels: Type: Enhancement
